---
- name: Setup machine for wordpress with mysql 5.6
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  become: true

  tasks:
  - name: "Put sudo passwordless"                                                                                                     
    become: true                                                                                                                      
    become_user: root                                                                                                                 
    lineinfile:                                                                                                                       
      dest: /etc/sudoers                                                                                                              
      state: present                                                                                                                  
      regexp: '^%sudo'                                                                                                                
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'                                                                                           
      validate: 'visudo -cf %s'  

  roles:
    - apache
    - mysql
    - php-fpm
    - wordpress
